# Generated by Django 5.0.6 on 2024-12-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenderapi.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biddingId', models.IntegerField(unique=True)),
                ('projectName', models.CharField(default='Metro Phase V 2024', max_length=255)),
                ('bidAmount', models.FloatField()),
                ('yearsToComplete', models.FloatField()),
                ('dateOfBidding', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapi.userprofile')),
            ],
        ),
    ]
